// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#ifndef _V4_UI_H
#define _V4_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_ScreenHome.h"
#include "ui_ScreenConfMain.h"
#include "ui_ScreenConfigurationGeneric.h"
#include "ui_ScreenAnalyse.h"
#include <stdio.h>

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_128379994);    // assets/main-menu.png
LV_IMG_DECLARE(ui_img_warning_png);    // assets/warning.png
LV_IMG_DECLARE(ui_img_info_png);    // assets/info.png
LV_IMG_DECLARE(ui_img_back30_png);    // assets/back30.png
LV_IMG_DECLARE(ui_img_foward30_png);    // assets/foward30.png
LV_IMG_DECLARE(ui_img_edit30_png);    // assets/edit30.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
