// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#include "ui.h"

void show_module_config_sensor(lv_event_t * e)
{  
	_ui_screen_change(&ui_ScreenConfigurationGeneric, LV_SCR_LOAD_ANIM_NONE, 100, 0,
                          &ui_ScreenConfigurationGeneric_screen_init);
	lv_label_set_text(ui_labelConfiguration,"Configuration Capteurs");
	lv_label_set_text(ui_confLabel1,"Frequences de lectures");
	lv_label_set_text(ui_confLabel2,"Nombre d echantillons");
	lv_label_set_text(ui_confLabel3,"Acquisition continue");// Your code here
	 
	
	lv_obj_add_flag( ui_rollerConfAlertes, LV_OBJ_FLAG_HIDDEN);		
}

void show_module_config_network(lv_event_t * e)
{
	// Your code here
}

void show_module_config_system(lv_event_t * e)
{
	_ui_screen_change(&ui_ScreenConfigurationGeneric, LV_SCR_LOAD_ANIM_NONE, 100, 0,
                          &ui_ScreenConfigurationGeneric_screen_init);
	lv_label_set_text(ui_labelConfiguration,"Configuration Systeme");
	lv_label_set_text(ui_confLabel1,"date");
	lv_label_set_text(ui_confLabel2,"heure");
	 
	
	lv_obj_add_flag( ui_rollerConfAlertes, LV_OBJ_FLAG_HIDDEN);		// Your code here
}

void confAlerteSelecModule(lv_event_t * e)
{
	// Your code here
	
	//uint32_t selected=lv_roller_get_selected(uic_rollerConfAlertes);
	//printf("selected %u",selected);
      //_ui_screen_change(&ui_ScreenConfigurationGeneric, LV_SCR_LOAD_ANIM_NONE, 100, 0,
                          //&ui_ScreenConfigurationGeneric_screen_init);
	 lv_obj_t * roller = lv_event_get_target(e);
        uint16_t idx = lv_roller_get_selected(roller);
        lv_roller_get_selected(roller);
        printf("idx=%u\n", (unsigned)idx);
		conf_roller_selected=idx;

		switch (idx)
		{
		case 0:
			/* batterie */
			lv_label_set_text(ui_labelConfiguration,"Configuration Alertes : batterie");
			lv_label_set_text(ui_confLabel1,"Surtension batterie (V):");
			lv_label_set_text(ui_confLabel3,"batterie dechargee (V):");
			lv_label_set_text(ui_confLabel3,"batterie chargee:");
			lv_textarea_set_text(ui_confValue1, "16.5");
			lv_textarea_set_text(ui_confValue2, "15.5");
			lv_textarea_set_text(ui_confValue3, "8.5");

			lv_obj_clear_flag(ui_confLabel2, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confLabel3, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confValue2, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confValue3, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confEditIcon2, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confEditIcon3, LV_OBJ_FLAG_HIDDEN);
			break;
		case 1:
			/* sortie 12v */
			lv_label_set_text(ui_labelConfiguration,"Configuration Alertes : sorties 12V");
			lv_label_set_text(ui_confLabel1,"seuil Icharge 12V1(A):");
			lv_label_set_text(ui_confLabel2,"seuil Icharge 12V3(A):");
			lv_label_set_text(ui_confLabel3,"seuil Icharge 12V2(A):");
			lv_textarea_set_text(ui_confValue1, "1.5");
			lv_textarea_set_text(ui_confValue2, "1.5");
			lv_textarea_set_text(ui_confValue3, "1.5");

			lv_obj_clear_flag(ui_confLabel2, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confLabel3, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confValue2, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confValue3, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confEditIcon2, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confEditIcon3, LV_OBJ_FLAG_HIDDEN);
			//ui_confLabel1;
			//ui_confLabel2;
			//ui_confLabel3;
			//ui_confValue1;
			//ui_confValue2;
			//ui_confValue3;
			break;
		case 2:
			/* sortie 48v */
			lv_label_set_text(ui_labelConfiguration,"Configuration Alertes : sorties 48V");
			lv_label_set_text(ui_confLabel1,"seuil Icharge 48(A):");
			lv_obj_add_flag(ui_confLabel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confLabel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confValue2, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confValue3, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confEditIcon2, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confEditIcon3, LV_OBJ_FLAG_HIDDEN);     /// Flags

            /*
			lv_obj_clear_flag(ui_confLabel2, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confLabel3, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confValue2, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confValue3, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confEditIcon2, LV_OBJ_FLAG_HIDDEN);
			lv_obj_clear_flag(ui_confEditIcon3, LV_OBJ_FLAG_HIDDEN);

			*/
    		//      /// Flags
			break;
		case 3:
			/* secteur 230 */
			lv_label_set_text(ui_labelConfiguration,"Configuration Alertes : secteur 230V");
			lv_label_set_text(ui_confLabel1,"seuil dec absence 230v (H):");
			lv_obj_add_flag(ui_confLabel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confLabel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confValue2, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confValue3, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confEditIcon2, LV_OBJ_FLAG_HIDDEN);     /// Flags
			lv_obj_add_flag(ui_confEditIcon3, LV_OBJ_FLAG_HIDDEN);     /// Flags
			break;
		
		default:
			break;
		}
	
}
/*
void keyboardConfManager(lv_event_t * e)
{
	// Your code here
}
*/
void keyboardConfManager(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * kb = lv_event_get_target(e);

    // Trace brute
    printf("keyboard event code = %u\n", (unsigned)code);

    // Afficher le texte de la touche (sur VALUE_CHANGED)
    if(code == LV_EVENT_VALUE_CHANGED) {
        uint16_t id = lv_btnmatrix_get_selected_btn(kb);
        const char * txt = lv_btnmatrix_get_btn_text(kb, id);
        printf("key: id=%u txt=%s\n", id, txt ? txt : "(null)");
    }

    // Masquer le clavier sur READY ou CANCEL
    if(code == LV_EVENT_READY || code == LV_EVENT_CANCEL) {
        //lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
        //lv_indev_reset(NULL, kb);
        //lv_obj_t * ta = lv_keyboard_get_textarea(kb);
        //if (ta) lv_obj_clear_state(ta, LV_STATE_FOCUSED);

		lv_obj_add_flag(ui_KeyboardConf, LV_OBJ_FLAG_HIDDEN); 


    }
}

 void ta_conf1_event_cb(lv_event_t * e)
{   
	printf("ta_conf1_event_cb \n");
    lv_event_code_t code = lv_event_get_code(e);
	printf("keyboard event code = %u\n", (unsigned)code);
    if(code == LV_EVENT_READY || code == LV_EVENT_CANCEL) {
        lv_obj_add_flag(ui_KeyboardConf, LV_OBJ_FLAG_HIDDEN);   // cacher le clavier
        lv_obj_clear_state(lv_event_get_target(e), LV_STATE_FOCUSED);
        // optionnel: détacher pour éviter réouverture automatique
        // lv_keyboard_set_textarea(ui_Keyboard1, NULL);
    }
}
void conf_back_controller(lv_event_t *e){
	
	
}
void conf_next_controller(lv_event_t *e){

	lv_obj_t * roller = lv_event_get_target(e);
        uint16_t idx = lv_roller_get_selected(roller);
        lv_roller_get_selected(roller);
        printf("conf_roller_selected=%u\n", (unsigned)conf_roller_selected);
	conf_page_index++;
	 printf("conf_page_index=%u\n", (unsigned)conf_page_index);
	switch (conf_page_index)
	{
	case 0:

		break;
	case 1:
		/* code */
		lv_label_set_text(ui_confLabel1,"tata");
	    lv_label_set_text(ui_confLabel2,"toto");
	    lv_label_set_text(ui_confLabel3,"tatie");// Your code here	
		break;
	case 2:

		break;
	case 3:

		break;
	default:
		break;
	}
	
}
void show_module_config_alerte(lv_event_t *e){

	 _ui_screen_change(&ui_ScreenConfigurationGeneric, LV_SCR_LOAD_ANIM_NONE, 100, 0,
                          &ui_ScreenConfigurationGeneric_screen_init);
	lv_label_set_text(ui_labelConfiguration,"Configuration Alertes : batterie");
	lv_label_set_text(ui_confLabel1,"Surtension batterie (V)");
	lv_label_set_text(ui_confLabel2,"Batterie chargee (V)");
	lv_label_set_text(ui_confLabel3,"batterie dechargee (V)");// Your code here	
    _ui_flag_modify(ui_rollerConfAlertes, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}

void home_alert_back_controller(lv_event_t * e)
{
	if(home_alerte_page_index>0)
	{


		home_alerte_page_index--;
	 	printf("home_alerte_page_index=%u\n", (unsigned)home_alerte_page_index);
		switch (home_alerte_page_index)
		{
			case 0:
			lv_label_set_text(ui_homeAlerteLabel,"absence tension 230V\n depuis 72H\n 06/08/25 18h02");
			lv_label_set_text(ui_Label6,"1/4");
			lv_img_set_src(ui_homeAlerteIcon, &ui_img_warning_png);
			break;
			case 1:
			/* code */
			lv_label_set_text(ui_homeAlerteLabel,"pic courant charge 12V_1:2.8A\n 06/08/25 18h02");
			lv_label_set_text(ui_Label6,"2/4");
			lv_img_set_src(ui_homeAlerteIcon, &ui_img_warning_png);
	    
			break;
			case 2:
        	lv_label_set_text(ui_homeAlerteLabel,"Serveur mqtt non accessible\n 05/08/25 04h05");
			lv_label_set_text(ui_Label6,"3/4");
			lv_img_set_src(ui_homeAlerteIcon, &ui_img_warning_png);
			break;
			case 3:
       		lv_label_set_text(ui_homeAlerteLabel,"Serveur MQTT accessible\n 05/08/25 04h05");
			lv_label_set_text(ui_Label6,"4/4");
			lv_img_set_src(ui_homeAlerteIcon, &ui_img_info_png);
			break;
			default:
			break;
		}
	}		
}
void home_alert_next_controller(lv_event_t * e)
{
	if(home_alerte_page_index<3)
	{


		home_alerte_page_index++;
	 	printf("home_alerte_page_index=%u\n", (unsigned)home_alerte_page_index);
		switch (home_alerte_page_index)
		{
			case 0:
			lv_label_set_text(ui_homeAlerteLabel,"absence tension 230V\n depuis 72H\n 06/08/25 18h02");
			lv_label_set_text(ui_Label6,"1/4");
			lv_img_set_src(ui_homeAlerteIcon, &ui_img_warning_png);
			break;
			case 1:
			/* code */
			lv_label_set_text(ui_homeAlerteLabel,"pic courant charge 12V_1:2.8A\n 06/08/25 18h02");
			lv_label_set_text(ui_Label6,"2/4");
			lv_img_set_src(ui_homeAlerteIcon, &ui_img_warning_png);
	    
			break;
			case 2:
        	lv_label_set_text(ui_homeAlerteLabel,"Serveur mqtt non accessible\n 05/08/25 04h05");
			lv_label_set_text(ui_Label6,"3/4");
			lv_img_set_src(ui_homeAlerteIcon, &ui_img_warning_png);
			break;
			case 3:
       		lv_label_set_text(ui_homeAlerteLabel,"Serveur MQTT accessible\n 05/08/25 04h05");
			lv_label_set_text(ui_Label6,"4/4");
			lv_img_set_src(ui_homeAlerteIcon, &ui_img_info_png);
			break;
			default:
			break;
		}
	}		
}

void slider_conf_value1_manager(lv_event_t * e)
{

}
void slider_conf_value2_manager(lv_event_t * e){

}


void analyse_graph_zoom_manager(lv_event_t * e)
{
	if (!graph_zoom_toogle)
	{
	
    graph_zoom_toogle=true;
	lv_obj_set_width(ui_Chart2, 237);
    lv_obj_set_height(ui_Chart2, 244);
    lv_obj_set_x(ui_Chart2, 74);
    lv_obj_set_y(ui_Chart2, 19);// Your code here

	lv_obj_set_width(ui_ConfSystem3, 480);
    lv_obj_set_height(ui_ConfSystem3, 316);
    lv_obj_set_x(ui_ConfSystem3, 3);
    lv_obj_set_y(ui_ConfSystem3, -2);// Your code here
    
    lv_obj_set_style_bg_color(ui_ConfSystem3, lv_color_hex(0x74849b), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(ui_labelTitreGrpah1, 74);
    lv_obj_set_y(ui_labelTitreGrpah1, -125);// Your code here


    lv_obj_set_x(ui_confNextIcon1, -148);
    lv_obj_set_y(ui_confNextIcon1, 136);// Your code here

	
    lv_obj_set_x(ui_confBackIcon1, -220);
    lv_obj_set_y(ui_confBackIcon1, 134);// Your code here

	
    lv_obj_set_x(ui_Label8, -185);
    lv_obj_set_y(ui_Label8, 135);// Your code here


    
    lv_obj_add_flag( ui_labelaAnalyse, LV_OBJ_FLAG_HIDDEN);     /// Flags
	lv_obj_add_flag( ui_datetimelabel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
	lv_obj_add_flag( ui_analyse, LV_OBJ_FLAG_HIDDEN);     /// Flags
	}
	else{
	graph_zoom_toogle=false;
	lv_obj_set_width(ui_Chart2, 166);
    lv_obj_set_height(ui_Chart2, 134);
    lv_obj_set_x(ui_Chart2, 110);
    lv_obj_set_y(ui_Chart2, 47);// Your code here

	lv_obj_set_width(ui_ConfSystem3, 323);
    lv_obj_set_height(ui_ConfSystem3, 191);
    lv_obj_set_x(ui_ConfSystem3, 71);
    lv_obj_set_y(ui_ConfSystem3, 56);// Your code here
    lv_obj_set_style_bg_color(ui_ConfSystem3, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(ui_labelTitreGrpah1, 39);
    lv_obj_set_y(ui_labelTitreGrpah1, -30);// Your code here


    lv_obj_set_x(ui_confNextIcon1, 6);
    lv_obj_set_y(ui_confNextIcon1, 130);// Your code here

	
    lv_obj_set_x(ui_confBackIcon1, -71);
    lv_obj_set_y(ui_confBackIcon1, 130);// Your code here

	
    lv_obj_set_x(ui_Label8, -32);
    lv_obj_set_y(ui_Label8, 129);// Your code here


    

	_ui_flag_modify(ui_labelaAnalyse, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
	_ui_flag_modify(ui_datetimelabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
	_ui_flag_modify(ui_analyse, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
	}


}
