// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void show_module_config_sensor(lv_event_t * e);
void show_module_config_network(lv_event_t * e);
void show_module_config_system(lv_event_t * e);
void confAlerteSelecModule(lv_event_t * e);
void keyboardConfManager(lv_event_t * e);

void conf_back_controller(lv_event_t *e);
void conf_next_controller(lv_event_t *e);
void show_module_config_alerte(lv_event_t *e);
void home_alert_back_controller(lv_event_t * e);
void home_alert_next_controller(lv_event_t * e);
void slider_conf_value1_manager(lv_event_t * e);
void slider_conf_value2_manager(lv_event_t * e);
 void ta_conf1_event_cb(lv_event_t * e);
static uint8_t conf_page_index=0;
static uint8_t home_alerte_page_index=0;
static uint8_t conf_roller_selected=0;
static bool graph_zoom_toogle=false;
void analyse_graph_zoom_manager(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
