// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHome
extern void ui_ScreenHome_screen_init(void);
extern void ui_ScreenHome_screen_destroy(void);
extern void ui_event_ScreenHome(lv_event_t * e);
extern lv_obj_t * ui_ScreenHome;
extern void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_AlerteContainer;
extern lv_obj_t * ui_AlerteContainerTitreLabel;
extern lv_obj_t * ui_datetimelabel;
extern void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_menuHomeLabel;
extern lv_obj_t * ui_menuAlertesLabel;
extern lv_obj_t * ui_menuExportLabel;
extern void ui_event_menuAnalysesLabel(lv_event_t * e);
extern lv_obj_t * ui_menuAnalysesLabel;
extern void ui_event_menuConfigLabel(lv_event_t * e);
extern lv_obj_t * ui_menuConfigLabel;
extern lv_obj_t * ui_homeAlerteContainer;
extern lv_obj_t * ui_homeAlerteIcon;
extern lv_obj_t * ui_homeAlerteLabel;
extern void ui_event_homeBackIcon(lv_event_t * e);
extern lv_obj_t * ui_homeBackIcon;
extern void ui_event_HomeNextIcon(lv_event_t * e);
extern lv_obj_t * ui_HomeNextIcon;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenHome;
extern lv_obj_t * uic_AlerteContainer;
extern lv_obj_t * uic_AlerteContainerTitreLabel;
extern lv_obj_t * uic_datetimelabel;
extern lv_obj_t * uic_menuHomeLabel;
extern lv_obj_t * uic_menuAlertesLabel;
extern lv_obj_t * uic_menuExportLabel;
extern lv_obj_t * uic_menuAnalysesLabel;
extern lv_obj_t * uic_menuConfigLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

