// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#include "ui.h"

lv_obj_t * uic_confNextIcon;
lv_obj_t * uic_confBackIcon;
lv_obj_t * uic_confCancelButton;
lv_obj_t * uic_confLabel3;
lv_obj_t * uic_confLabel2;
lv_obj_t * uic_confLabel1;
lv_obj_t * uic_labelConfigurateurAlertes;
lv_obj_t * uic_rollerConfAlertes;
lv_obj_t * ui_ScreenConfigurationGeneric;
lv_obj_t * ui_ScreenHomeLabel1;
lv_obj_t * ui_datetimelabel3;
lv_obj_t * ui_ConfSystem1;
lv_obj_t * ui_rollerConfAlertes;
lv_obj_t * ui_Image2;
lv_obj_t * ui_ConfSystem2;
lv_obj_t * ui_labelConfiguration;
lv_obj_t * ui_confLabel1;
lv_obj_t * ui_confLabel2;
lv_obj_t * ui_confLabel3;
lv_obj_t * ui_confValue1;
lv_obj_t * ui_confValue2;
lv_obj_t * ui_confValue3;
lv_obj_t * ui_confCancelButton;
lv_obj_t * ui_Label2;
lv_obj_t * ui_confSaveButton1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_confBackIcon;
lv_obj_t * ui_Label4;
lv_obj_t * ui_confNextIcon;
lv_obj_t * ui_confEditIcon1;
lv_obj_t * ui_confEditIcon2;
lv_obj_t * ui_confEditIcon3;
lv_obj_t * ui_KeyboardConf;
lv_obj_t * ui_Slider1Conf;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_menuHomeLabel1;
lv_obj_t * ui_menuAlertesLabel1;
lv_obj_t * ui_menuExportLabel1;
lv_obj_t * ui_menuAnalysesLabel1;
lv_obj_t * ui_menuConfigLabel1;
lv_obj_t * ui_Slider2Conf;
lv_obj_t * ui_symboleConfOkValue1;
lv_obj_t * ui_symboleConfOkValue2;

// event funtions
void ui_event_rollerConfAlertes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        confAlerteSelecModule(e);
    }
}

void ui_event_Image2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuHomeLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuAlertesLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuExportLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuAnalysesLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuConfigLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_confValue1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED||LV_EVENT_INSERT) {
        ta_conf1_event_cb(e);
    }
}

void ui_event_confBackIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        conf_back_controller(e);
    }
}

void ui_event_confNextIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        conf_next_controller(e);
    }
}

void ui_event_confEditIcon1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardConf, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_KeyboardConf(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        keyboardConfManager(e);
    }
}

void ui_event_Slider1Conf(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_conf_value1_manager(e);
    }
}

void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_menuHomeLabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenHome_screen_init);
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuHomeLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAlertesLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuExportLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAnalysesLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuConfigLabel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_menuConfigLabel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenConfMain, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenConfMain_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Slider2Conf(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_conf_value2_manager(e);
    }
}

// build funtions

void ui_ScreenConfigurationGeneric_screen_init(void)
{
    ui_ScreenConfigurationGeneric = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenConfigurationGeneric, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenConfigurationGeneric, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenConfigurationGeneric, lv_color_hex(0x195FC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenConfigurationGeneric, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScreenConfigurationGeneric, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreenConfigurationGeneric, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenConfigurationGeneric, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenHomeLabel1 = lv_label_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_ScreenHomeLabel1, lv_pct(98));
    lv_obj_set_height(ui_ScreenHomeLabel1, lv_pct(31));
    lv_obj_set_x(ui_ScreenHomeLabel1, 1);
    lv_obj_set_y(ui_ScreenHomeLabel1, -104);
    lv_obj_set_align(ui_ScreenHomeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenHomeLabel1, "\nVCITY  DASHBOARD ");
    lv_obj_set_style_text_color(ui_ScreenHomeLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenHomeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenHomeLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ScreenHomeLabel1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenHomeLabel1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenHomeLabel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenHomeLabel1, lv_color_hex(0x71AA38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHomeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ScreenHomeLabel1, lv_color_hex(0x8A7E7E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ScreenHomeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScreenHomeLabel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScreenHomeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ScreenHomeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ScreenHomeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenHomeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenHomeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenHomeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenHomeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datetimelabel3 = lv_label_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_datetimelabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_datetimelabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datetimelabel3, -185);
    lv_obj_set_y(ui_datetimelabel3, 148);
    lv_obj_set_align(ui_datetimelabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_datetimelabel3, "08/08/2025 11h27 	");
    lv_obj_set_style_text_color(ui_datetimelabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_datetimelabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_datetimelabel3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_datetimelabel3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_datetimelabel3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_datetimelabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_datetimelabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_datetimelabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_datetimelabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_datetimelabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfSystem1 = lv_obj_create(ui_ScreenConfigurationGeneric);
    lv_obj_remove_style_all(ui_ConfSystem1);
    lv_obj_set_width(ui_ConfSystem1, 323);
    lv_obj_set_height(ui_ConfSystem1, 191);
    lv_obj_set_x(ui_ConfSystem1, 71);
    lv_obj_set_y(ui_ConfSystem1, 56);
    lv_obj_set_align(ui_ConfSystem1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConfSystem1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfSystem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfSystem1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ConfSystem1, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfSystem1, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfSystem1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfSystem1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ConfSystem1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfSystem1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ConfSystem1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ConfSystem1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ConfSystem1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ConfSystem1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_rollerConfAlertes = lv_roller_create(ui_ScreenConfigurationGeneric);
    lv_roller_set_options(ui_rollerConfAlertes, "Batterie\nSortie 12V\nSortie 48V\nSecteur 230V", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_rollerConfAlertes, 120);
    lv_obj_set_width(ui_rollerConfAlertes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rollerConfAlertes, -168);
    lv_obj_set_y(ui_rollerConfAlertes, 36);
    lv_obj_set_align(ui_rollerConfAlertes, LV_ALIGN_CENTER);
    lv_obj_set_style_text_letter_space(ui_rollerConfAlertes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerConfAlertes, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rollerConfAlertes, lv_color_hex(0x716F6D), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerConfAlertes, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_ScreenConfigurationGeneric);
    lv_img_set_src(ui_Image2, &ui_img_128379994);
    lv_obj_set_width(ui_Image2, 50);
    lv_obj_set_height(ui_Image2, 30);
    lv_obj_set_x(ui_Image2, -190);
    lv_obj_set_y(ui_Image2, -63);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_ConfSystem2 = lv_obj_create(ui_ScreenConfigurationGeneric);
    lv_obj_remove_style_all(ui_ConfSystem2);
    lv_obj_set_width(ui_ConfSystem2, 323);
    lv_obj_set_height(ui_ConfSystem2, 39);
    lv_obj_set_x(ui_ConfSystem2, 70);
    lv_obj_set_y(ui_ConfSystem2, -60);
    lv_obj_set_align(ui_ConfSystem2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConfSystem2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfSystem2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfSystem2, lv_color_hex(0xE27708), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfSystem2, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ConfSystem2, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfSystem2, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfSystem2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfSystem2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_width(ui_ConfSystem2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ConfSystem2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ConfSystem2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ConfSystem2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_labelConfiguration = lv_label_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_labelConfiguration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelConfiguration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelConfiguration, 76);
    lv_obj_set_y(ui_labelConfiguration, -60);
    lv_obj_set_align(ui_labelConfiguration, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelConfiguration, "Configuration Alertes : batterie");
    lv_obj_set_style_text_color(ui_labelConfiguration, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelConfiguration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confLabel1 = lv_label_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_confLabel1, 170);
    lv_obj_set_height(ui_confLabel1, 35);
    lv_obj_set_x(ui_confLabel1, -2);
    lv_obj_set_y(ui_confLabel1, -2);
    lv_obj_set_align(ui_confLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confLabel1, "Surtension Batterie");
    lv_obj_set_style_text_color(ui_confLabel1, lv_color_hex(0x595858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confLabel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confLabel2 = lv_label_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_confLabel2, 170);
    lv_obj_set_height(ui_confLabel2, 35);
    lv_obj_set_x(ui_confLabel2, -3);
    lv_obj_set_y(ui_confLabel2, 86);
    lv_obj_set_align(ui_confLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confLabel2, "Batterie dechargee");
    lv_obj_set_style_text_color(ui_confLabel2, lv_color_hex(0x595858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confLabel3 = lv_label_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_confLabel3, 170);
    lv_obj_set_height(ui_confLabel3, 35);
    lv_obj_set_x(ui_confLabel3, -3);
    lv_obj_set_y(ui_confLabel3, 38);
    lv_obj_set_align(ui_confLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confLabel3, "Batterie chargee");
    lv_obj_set_style_text_color(ui_confLabel3, lv_color_hex(0x595858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confLabel3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confValue1 = lv_textarea_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_confValue1, 55);
    lv_obj_set_height(ui_confValue1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_confValue1, 122);
    lv_obj_set_y(ui_confValue1, -12);
    lv_obj_set_align(ui_confValue1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_confValue1, 4);
    lv_textarea_set_text(ui_confValue1, "16.5");
    lv_textarea_set_one_line(ui_confValue1, true);
    lv_obj_set_style_text_color(ui_confValue1, lv_color_hex(0x595858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_confValue1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_confValue1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_confValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confValue1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_confValue1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_confValue1, lv_color_hex(0xF4F4FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_confValue1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_confValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_confValue1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_confValue1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_confValue1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_confValue1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_confValue1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confValue2 = lv_textarea_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_confValue2, 55);
    lv_obj_set_height(ui_confValue2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_confValue2, 121);
    lv_obj_set_y(ui_confValue2, 33);
    lv_obj_set_align(ui_confValue2, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_confValue2, 4);
    lv_textarea_set_text(ui_confValue2, "15.5");
    lv_textarea_set_one_line(ui_confValue2, true);
    lv_obj_set_style_text_color(ui_confValue2, lv_color_hex(0x595858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_confValue2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_confValue2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_confValue2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confValue2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_confValue2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_confValue2, lv_color_hex(0xF4F4FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_confValue2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_confValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_confValue2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_confValue2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_confValue2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_confValue2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_confValue2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confValue3 = lv_textarea_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_confValue3, 55);
    lv_obj_set_height(ui_confValue3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_confValue3, 121);
    lv_obj_set_y(ui_confValue3, 78);
    lv_obj_set_align(ui_confValue3, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_confValue3, 4);
    lv_textarea_set_text(ui_confValue3, "8.5");
    lv_textarea_set_one_line(ui_confValue3, true);
    lv_obj_set_style_text_color(ui_confValue3, lv_color_hex(0x595858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_confValue3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_confValue3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_confValue3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confValue3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_confValue3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_confValue3, lv_color_hex(0xF4F4FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_confValue3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_confValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_confValue3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_confValue3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_confValue3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_confValue3, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_confValue3, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confCancelButton = lv_btn_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_confCancelButton, 72);
    lv_obj_set_height(ui_confCancelButton, 36);
    lv_obj_set_x(ui_confCancelButton, 98);
    lv_obj_set_y(ui_confCancelButton, 130);
    lv_obj_set_align(ui_confCancelButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confCancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_confCancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_confCancelButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_confCancelButton, lv_color_hex(0x807E7E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confCancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_confCancelButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -1);
    lv_obj_set_y(ui_Label2, 2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "annuler");

    ui_confSaveButton1 = lv_btn_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_confSaveButton1, 72);
    lv_obj_set_height(ui_confSaveButton1, 36);
    lv_obj_set_x(ui_confSaveButton1, 193);
    lv_obj_set_y(ui_confSaveButton1, 130);
    lv_obj_set_align(ui_confSaveButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confSaveButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_confSaveButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_confSaveButton1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_confSaveButton1, lv_color_hex(0x807E7E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confSaveButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_confSaveButton1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, 1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "valider");

    ui_confBackIcon = lv_img_create(ui_ScreenConfigurationGeneric);
    lv_img_set_src(ui_confBackIcon, &ui_img_back30_png);
    lv_obj_set_width(ui_confBackIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confBackIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confBackIcon, -71);
    lv_obj_set_y(ui_confBackIcon, 129);
    lv_obj_set_align(ui_confBackIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confBackIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_confBackIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -32);
    lv_obj_set_y(ui_Label4, 129);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "1/3");

    ui_confNextIcon = lv_img_create(ui_ScreenConfigurationGeneric);
    lv_img_set_src(ui_confNextIcon, &ui_img_foward30_png);
    lv_obj_set_width(ui_confNextIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confNextIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confNextIcon, 6);
    lv_obj_set_y(ui_confNextIcon, 130);
    lv_obj_set_align(ui_confNextIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confNextIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_confNextIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_confEditIcon1 = lv_img_create(ui_ScreenConfigurationGeneric);
    lv_img_set_src(ui_confEditIcon1, &ui_img_edit30_png);
    lv_obj_set_width(ui_confEditIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confEditIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confEditIcon1, 201);
    lv_obj_set_y(ui_confEditIcon1, -14);
    lv_obj_set_align(ui_confEditIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confEditIcon1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE |
                    LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_confEditIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_confEditIcon2 = lv_img_create(ui_ScreenConfigurationGeneric);
    lv_img_set_src(ui_confEditIcon2, &ui_img_edit30_png);
    lv_obj_set_width(ui_confEditIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confEditIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confEditIcon2, 199);
    lv_obj_set_y(ui_confEditIcon2, 28);
    lv_obj_set_align(ui_confEditIcon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confEditIcon2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE |
                    LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_confEditIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_confEditIcon3 = lv_img_create(ui_ScreenConfigurationGeneric);
    lv_img_set_src(ui_confEditIcon3, &ui_img_edit30_png);
    lv_obj_set_width(ui_confEditIcon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confEditIcon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confEditIcon3, 199);
    lv_obj_set_y(ui_confEditIcon3, 75);
    lv_obj_set_align(ui_confEditIcon3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confEditIcon3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE |
                    LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_confEditIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardConf = lv_keyboard_create(ui_ScreenConfigurationGeneric);
    lv_keyboard_set_mode(ui_KeyboardConf, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardConf, 300);
    lv_obj_set_height(ui_KeyboardConf, 217);
    lv_obj_set_x(ui_KeyboardConf, -62);
    lv_obj_set_y(ui_KeyboardConf, -3);
    lv_obj_set_align(ui_KeyboardConf, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardConf, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_KeyboardConf, lv_color_hex(0x9EA6CB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardConf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_KeyboardConf, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KeyboardConf, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KeyboardConf, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KeyboardConf, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_KeyboardConf, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_KeyboardConf, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_KeyboardConf, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KeyboardConf, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Slider1Conf = lv_slider_create(ui_ScreenConfigurationGeneric);
    lv_slider_set_value(ui_Slider1Conf, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1Conf) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1Conf, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1Conf, 72);
    lv_obj_set_height(ui_Slider1Conf, 20);
    lv_obj_set_x(ui_Slider1Conf, 178);
    lv_obj_set_y(ui_Slider1Conf, -13);
    lv_obj_set_align(ui_Slider1Conf, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider1Conf, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Slider1Conf, lv_color_hex(0xC1BCBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1Conf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1Conf, lv_color_hex(0x6D6E6D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1Conf, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_Panel2, 175);
    lv_obj_set_height(ui_Panel2, 239);
    lv_obj_set_x(ui_Panel2, -141);
    lv_obj_set_y(ui_Panel2, 16);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_menuHomeLabel1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_menuHomeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuHomeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuHomeLabel1, -3);
    lv_obj_set_y(ui_menuHomeLabel1, -72);
    lv_obj_set_align(ui_menuHomeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuHomeLabel1, "home");
    lv_obj_add_flag(ui_menuHomeLabel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuHomeLabel1, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuHomeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuHomeLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuAlertesLabel1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_menuAlertesLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAlertesLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuAlertesLabel1, -157);
    lv_obj_set_y(ui_menuAlertesLabel1, -26);
    lv_obj_set_align(ui_menuAlertesLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAlertesLabel1, "Alertes");
    lv_obj_set_style_text_color(ui_menuAlertesLabel1, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuAlertesLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAlertesLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuExportLabel1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_menuExportLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuExportLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuExportLabel1, 0);
    lv_obj_set_y(ui_menuExportLabel1, -27);
    lv_obj_set_align(ui_menuExportLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuExportLabel1, "Export");
    lv_obj_set_style_text_color(ui_menuExportLabel1, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuExportLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuExportLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuAnalysesLabel1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_menuAnalysesLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAnalysesLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuAnalysesLabel1, 2);
    lv_obj_set_y(ui_menuAnalysesLabel1, 24);
    lv_obj_set_align(ui_menuAnalysesLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAnalysesLabel1, "Analyses");
    lv_obj_add_flag(ui_menuAnalysesLabel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuAnalysesLabel1, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuAnalysesLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAnalysesLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuConfigLabel1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_menuConfigLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuConfigLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuConfigLabel1, 6);
    lv_obj_set_y(ui_menuConfigLabel1, 76);
    lv_obj_set_align(ui_menuConfigLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuConfigLabel1, "Settings");
    lv_obj_add_flag(ui_menuConfigLabel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuConfigLabel1, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuConfigLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuConfigLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2Conf = lv_slider_create(ui_ScreenConfigurationGeneric);
    lv_slider_set_value(ui_Slider2Conf, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2Conf) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2Conf, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2Conf, 72);
    lv_obj_set_height(ui_Slider2Conf, 20);
    lv_obj_set_x(ui_Slider2Conf, 179);
    lv_obj_set_y(ui_Slider2Conf, 30);
    lv_obj_set_align(ui_Slider2Conf, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider2Conf, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Slider2Conf, lv_color_hex(0xC1BCBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2Conf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2Conf, lv_color_hex(0x6D6E6D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2Conf, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_symboleConfOkValue1 = lv_obj_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_symboleConfOkValue1, 20);
    lv_obj_set_height(ui_symboleConfOkValue1, 20);
    lv_obj_set_x(ui_symboleConfOkValue1, 201);
    lv_obj_set_y(ui_symboleConfOkValue1, -13);
    lv_obj_set_align(ui_symboleConfOkValue1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_symboleConfOkValue1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_symboleConfOkValue1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_symboleConfOkValue1, lv_color_hex(0x356C42), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_symboleConfOkValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_symboleConfOkValue2 = lv_obj_create(ui_ScreenConfigurationGeneric);
    lv_obj_set_width(ui_symboleConfOkValue2, 20);
    lv_obj_set_height(ui_symboleConfOkValue2, 20);
    lv_obj_set_x(ui_symboleConfOkValue2, 200);
    lv_obj_set_y(ui_symboleConfOkValue2, 30);
    lv_obj_set_align(ui_symboleConfOkValue2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_symboleConfOkValue2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_symboleConfOkValue2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_symboleConfOkValue2, lv_color_hex(0x356C42), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_symboleConfOkValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_rollerConfAlertes, ui_event_rollerConfAlertes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confValue1, ui_event_confValue1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confBackIcon, ui_event_confBackIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confNextIcon, ui_event_confNextIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confEditIcon1, ui_event_confEditIcon1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardConf, ui_confValue1);
    lv_obj_add_event_cb(ui_KeyboardConf, ui_event_KeyboardConf, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1Conf, ui_event_Slider1Conf, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuHomeLabel1, ui_event_menuHomeLabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuConfigLabel1, ui_event_menuConfigLabel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2Conf, ui_event_Slider2Conf, LV_EVENT_ALL, NULL);
    uic_rollerConfAlertes = ui_rollerConfAlertes;
    uic_labelConfigurateurAlertes = ui_labelConfiguration;
    uic_confLabel1 = ui_confLabel1;
    uic_confLabel2 = ui_confLabel2;
    uic_confLabel3 = ui_confLabel3;
    uic_confCancelButton = ui_confCancelButton;
    uic_confBackIcon = ui_confBackIcon;
    uic_confNextIcon = ui_confNextIcon;

}

void ui_ScreenConfigurationGeneric_screen_destroy(void)
{
    if(ui_ScreenConfigurationGeneric) lv_obj_del(ui_ScreenConfigurationGeneric);

    // NULL screen variables
    ui_ScreenConfigurationGeneric = NULL;
    ui_ScreenHomeLabel1 = NULL;
    ui_datetimelabel3 = NULL;
    ui_ConfSystem1 = NULL;
    uic_rollerConfAlertes = NULL;
    ui_rollerConfAlertes = NULL;
    ui_Image2 = NULL;
    ui_ConfSystem2 = NULL;
    uic_labelConfigurateurAlertes = NULL;
    ui_labelConfiguration = NULL;
    uic_confLabel1 = NULL;
    ui_confLabel1 = NULL;
    uic_confLabel2 = NULL;
    ui_confLabel2 = NULL;
    uic_confLabel3 = NULL;
    ui_confLabel3 = NULL;
    ui_confValue1 = NULL;
    ui_confValue2 = NULL;
    ui_confValue3 = NULL;
    uic_confCancelButton = NULL;
    ui_confCancelButton = NULL;
    ui_Label2 = NULL;
    ui_confSaveButton1 = NULL;
    ui_Label3 = NULL;
    uic_confBackIcon = NULL;
    ui_confBackIcon = NULL;
    ui_Label4 = NULL;
    uic_confNextIcon = NULL;
    ui_confNextIcon = NULL;
    ui_confEditIcon1 = NULL;
    ui_confEditIcon2 = NULL;
    ui_confEditIcon3 = NULL;
    ui_KeyboardConf = NULL;
    ui_Slider1Conf = NULL;
    ui_Panel2 = NULL;
    ui_menuHomeLabel1 = NULL;
    ui_menuAlertesLabel1 = NULL;
    ui_menuExportLabel1 = NULL;
    ui_menuAnalysesLabel1 = NULL;
    ui_menuConfigLabel1 = NULL;
    ui_Slider2Conf = NULL;
    ui_symboleConfOkValue1 = NULL;
    ui_symboleConfOkValue2 = NULL;

}
