// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#include "ui.h"

lv_obj_t * ui_ScreenAnalyse;
lv_obj_t * ui_ScreenHomeLabel2;
lv_obj_t * ui_datetimelabel2;
lv_obj_t * ui_ConfSystem3;
lv_obj_t * ui_rollerConfAlertes1;
lv_obj_t * ui_Image4;
lv_obj_t * ui_analyse;
lv_obj_t * ui_labelaAnalyse;
lv_obj_t * ui_confBackIcon1;
lv_obj_t * ui_Label8;
lv_obj_t * ui_confNextIcon1;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_menuHomeLabel3;
lv_obj_t * ui_menuAlertesLabel3;
lv_obj_t * ui_menuExportLabel3;
lv_obj_t * ui_menuAnalysesLabel3;
lv_obj_t * ui_menuConfigLabel3;
lv_obj_t * ui_labelTitreGrpah1;
lv_obj_t * ui_Chart2;

// event funtions
void ui_event_rollerConfAlertes1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        confAlerteSelecModule(e);
    }
}

void ui_event_Image4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuHomeLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuAlertesLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuExportLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuAnalysesLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuConfigLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_confBackIcon1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        conf_back_controller(e);
    }
}

void ui_event_confNextIcon1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        conf_next_controller(e);
    }
}

void ui_event_Panel4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_menuHomeLabel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenHome_screen_init);
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuHomeLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAlertesLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuExportLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAnalysesLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuConfigLabel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_menuConfigLabel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenConfMain, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenConfMain_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Chart2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        analyse_graph_zoom_manager(e);
    }
}

// build funtions

void ui_ScreenAnalyse_screen_init(void)
{
    ui_ScreenAnalyse = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAnalyse, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenAnalyse, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenAnalyse, lv_color_hex(0x195FC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAnalyse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScreenAnalyse, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreenAnalyse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenAnalyse, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenHomeLabel2 = lv_label_create(ui_ScreenAnalyse);
    lv_obj_set_width(ui_ScreenHomeLabel2, lv_pct(98));
    lv_obj_set_height(ui_ScreenHomeLabel2, lv_pct(31));
    lv_obj_set_x(ui_ScreenHomeLabel2, 1);
    lv_obj_set_y(ui_ScreenHomeLabel2, -104);
    lv_obj_set_align(ui_ScreenHomeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenHomeLabel2, "\nVCITY  DASHBOARD ");
    lv_obj_set_style_text_color(ui_ScreenHomeLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenHomeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenHomeLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ScreenHomeLabel2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenHomeLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenHomeLabel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenHomeLabel2, lv_color_hex(0x71AA38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHomeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ScreenHomeLabel2, lv_color_hex(0x8A7E7E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ScreenHomeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScreenHomeLabel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScreenHomeLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ScreenHomeLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ScreenHomeLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenHomeLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenHomeLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenHomeLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenHomeLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datetimelabel2 = lv_label_create(ui_ScreenAnalyse);
    lv_obj_set_width(ui_datetimelabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_datetimelabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datetimelabel2, -185);
    lv_obj_set_y(ui_datetimelabel2, 148);
    lv_obj_set_align(ui_datetimelabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_datetimelabel2, "08/08/2025 11h27 	");
    lv_obj_set_style_text_color(ui_datetimelabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_datetimelabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_datetimelabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_datetimelabel2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_datetimelabel2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_datetimelabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_datetimelabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_datetimelabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_datetimelabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_datetimelabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfSystem3 = lv_obj_create(ui_ScreenAnalyse);
    lv_obj_remove_style_all(ui_ConfSystem3);
    lv_obj_set_width(ui_ConfSystem3, 323);
    lv_obj_set_height(ui_ConfSystem3, 191);
    lv_obj_set_x(ui_ConfSystem3, 71);
    lv_obj_set_y(ui_ConfSystem3, 56);
    lv_obj_set_align(ui_ConfSystem3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConfSystem3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfSystem3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfSystem3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ConfSystem3, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfSystem3, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfSystem3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfSystem3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ConfSystem3, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfSystem3, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ConfSystem3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ConfSystem3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ConfSystem3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ConfSystem3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_rollerConfAlertes1 = lv_roller_create(ui_ScreenAnalyse);
    lv_roller_set_options(ui_rollerConfAlertes1, "Batterie\nSortie 12V\nSortie 48V\nSecteur 230V", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_rollerConfAlertes1, 120);
    lv_obj_set_width(ui_rollerConfAlertes1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rollerConfAlertes1, -168);
    lv_obj_set_y(ui_rollerConfAlertes1, 36);
    lv_obj_set_align(ui_rollerConfAlertes1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_letter_space(ui_rollerConfAlertes1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_rollerConfAlertes1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_rollerConfAlertes1, lv_color_hex(0x716F6D), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerConfAlertes1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_ScreenAnalyse);
    lv_img_set_src(ui_Image4, &ui_img_128379994);
    lv_obj_set_width(ui_Image4, 50);
    lv_obj_set_height(ui_Image4, 30);
    lv_obj_set_x(ui_Image4, -190);
    lv_obj_set_y(ui_Image4, -63);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_analyse = lv_obj_create(ui_ScreenAnalyse);
    lv_obj_remove_style_all(ui_analyse);
    lv_obj_set_width(ui_analyse, 323);
    lv_obj_set_height(ui_analyse, 39);
    lv_obj_set_x(ui_analyse, 70);
    lv_obj_set_y(ui_analyse, -60);
    lv_obj_set_align(ui_analyse, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_analyse, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_analyse, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_analyse, lv_color_hex(0xE27708), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_analyse, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_analyse, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_analyse, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_analyse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_analyse, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_width(ui_analyse, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_analyse, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_analyse, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_analyse, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_labelaAnalyse = lv_label_create(ui_ScreenAnalyse);
    lv_obj_set_width(ui_labelaAnalyse, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelaAnalyse, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelaAnalyse, 76);
    lv_obj_set_y(ui_labelaAnalyse, -60);
    lv_obj_set_align(ui_labelaAnalyse, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelaAnalyse, "Annalyse: batterie");
    lv_obj_set_style_text_color(ui_labelaAnalyse, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelaAnalyse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confBackIcon1 = lv_img_create(ui_ScreenAnalyse);
    lv_img_set_src(ui_confBackIcon1, &ui_img_back30_png);
    lv_obj_set_width(ui_confBackIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confBackIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confBackIcon1, -71);
    lv_obj_set_y(ui_confBackIcon1, 129);
    lv_obj_set_align(ui_confBackIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confBackIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_confBackIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_ScreenAnalyse);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -32);
    lv_obj_set_y(ui_Label8, 129);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "1/3");

    ui_confNextIcon1 = lv_img_create(ui_ScreenAnalyse);
    lv_img_set_src(ui_confNextIcon1, &ui_img_foward30_png);
    lv_obj_set_width(ui_confNextIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confNextIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confNextIcon1, 6);
    lv_obj_set_y(ui_confNextIcon1, 130);
    lv_obj_set_align(ui_confNextIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confNextIcon1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE |
                    LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_confNextIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_ScreenAnalyse);
    lv_obj_set_width(ui_Panel4, 175);
    lv_obj_set_height(ui_Panel4, 239);
    lv_obj_set_x(ui_Panel4, -141);
    lv_obj_set_y(ui_Panel4, 16);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_menuHomeLabel3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_menuHomeLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuHomeLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuHomeLabel3, -3);
    lv_obj_set_y(ui_menuHomeLabel3, -72);
    lv_obj_set_align(ui_menuHomeLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuHomeLabel3, "home");
    lv_obj_add_flag(ui_menuHomeLabel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuHomeLabel3, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuHomeLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuHomeLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuAlertesLabel3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_menuAlertesLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAlertesLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuAlertesLabel3, -157);
    lv_obj_set_y(ui_menuAlertesLabel3, -26);
    lv_obj_set_align(ui_menuAlertesLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAlertesLabel3, "Alertes");
    lv_obj_set_style_text_color(ui_menuAlertesLabel3, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuAlertesLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAlertesLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuExportLabel3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_menuExportLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuExportLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuExportLabel3, 0);
    lv_obj_set_y(ui_menuExportLabel3, -27);
    lv_obj_set_align(ui_menuExportLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuExportLabel3, "Export");
    lv_obj_set_style_text_color(ui_menuExportLabel3, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuExportLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuExportLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuAnalysesLabel3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_menuAnalysesLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAnalysesLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuAnalysesLabel3, 2);
    lv_obj_set_y(ui_menuAnalysesLabel3, 24);
    lv_obj_set_align(ui_menuAnalysesLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAnalysesLabel3, "Analyses");
    lv_obj_add_flag(ui_menuAnalysesLabel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuAnalysesLabel3, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuAnalysesLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAnalysesLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuConfigLabel3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_menuConfigLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuConfigLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuConfigLabel3, 6);
    lv_obj_set_y(ui_menuConfigLabel3, 76);
    lv_obj_set_align(ui_menuConfigLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuConfigLabel3, "Settings");
    lv_obj_add_flag(ui_menuConfigLabel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuConfigLabel3, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuConfigLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuConfigLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTitreGrpah1 = lv_label_create(ui_ScreenAnalyse);
    lv_obj_set_width(ui_labelTitreGrpah1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTitreGrpah1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTitreGrpah1, 39);
    lv_obj_set_y(ui_labelTitreGrpah1, -30);
    lv_obj_set_align(ui_labelTitreGrpah1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTitreGrpah1, "tension (mV),courant(mA )batterie");
    lv_obj_set_style_text_color(ui_labelTitreGrpah1, lv_color_hex(0x4F4C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTitreGrpah1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_ScreenAnalyse);
    lv_obj_set_width(ui_Chart2, 166);
    lv_obj_set_height(ui_Chart2, 134);
    lv_obj_set_x(ui_Chart2, 110);
    lv_obj_set_y(ui_Chart2, 47);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart2, 12);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10000, 13500);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 800, 2500);
    lv_chart_set_div_line_count(ui_Chart2, 6, 12);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 12, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x90B6F2),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 11200, 12200, 13000, 13200, 13000, 12990, 12800, 12700, 12650, 12500, 12450, 12400 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_chart_series_t * ui_Chart2_series_2 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xF03D3D),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart2_series_2_array[] = { 1200, 1200, 1300, 1400, 900, 1700, 1550, 1490, 1100, 1100, 1270, 1400 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_2, ui_Chart2_series_2_array);
    lv_obj_set_style_radius(ui_Chart2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Chart2, &lv_font_montserrat_10, LV_PART_TICKS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_rollerConfAlertes1, ui_event_rollerConfAlertes1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confBackIcon1, ui_event_confBackIcon1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confNextIcon1, ui_event_confNextIcon1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuHomeLabel3, ui_event_menuHomeLabel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuConfigLabel3, ui_event_menuConfigLabel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel4, ui_event_Panel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Chart2, ui_event_Chart2, LV_EVENT_ALL, NULL);

}

void ui_ScreenAnalyse_screen_destroy(void)
{
    if(ui_ScreenAnalyse) lv_obj_del(ui_ScreenAnalyse);

    // NULL screen variables
    ui_ScreenAnalyse = NULL;
    ui_ScreenHomeLabel2 = NULL;
    ui_datetimelabel2 = NULL;
    ui_ConfSystem3 = NULL;
    ui_rollerConfAlertes1 = NULL;
    ui_Image4 = NULL;
    ui_analyse = NULL;
    ui_labelaAnalyse = NULL;
    ui_confBackIcon1 = NULL;
    ui_Label8 = NULL;
    ui_confNextIcon1 = NULL;
    ui_Panel4 = NULL;
    ui_menuHomeLabel3 = NULL;
    ui_menuAlertesLabel3 = NULL;
    ui_menuExportLabel3 = NULL;
    ui_menuAnalysesLabel3 = NULL;
    ui_menuConfigLabel3 = NULL;
    ui_labelTitreGrpah1 = NULL;
    ui_Chart2 = NULL;

}
