// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#ifndef UI_SCREENANALYSE_H
#define UI_SCREENANALYSE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAnalyse
extern void ui_ScreenAnalyse_screen_init(void);
extern void ui_ScreenAnalyse_screen_destroy(void);
extern lv_obj_t * ui_ScreenAnalyse;
extern lv_obj_t * ui_ScreenHomeLabel2;
extern lv_obj_t * ui_datetimelabel2;
extern lv_obj_t * ui_ConfSystem3;
extern void ui_event_rollerConfAlertes1(lv_event_t * e);
extern lv_obj_t * ui_rollerConfAlertes1;
extern void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_analyse;
extern lv_obj_t * ui_labelaAnalyse;
extern void ui_event_confBackIcon1(lv_event_t * e);
extern lv_obj_t * ui_confBackIcon1;
extern lv_obj_t * ui_Label8;
extern void ui_event_confNextIcon1(lv_event_t * e);
extern lv_obj_t * ui_confNextIcon1;
extern void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
extern void ui_event_menuHomeLabel3(lv_event_t * e);
extern lv_obj_t * ui_menuHomeLabel3;
extern lv_obj_t * ui_menuAlertesLabel3;
extern lv_obj_t * ui_menuExportLabel3;
extern lv_obj_t * ui_menuAnalysesLabel3;
extern void ui_event_menuConfigLabel3(lv_event_t * e);
extern lv_obj_t * ui_menuConfigLabel3;
extern lv_obj_t * ui_labelTitreGrpah1;
extern void ui_event_Chart2(lv_event_t * e);
extern lv_obj_t * ui_Chart2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

