// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#ifndef UI_SCREENCONFIGURATIONGENERIC_H
#define UI_SCREENCONFIGURATIONGENERIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenConfigurationGeneric
extern void ui_ScreenConfigurationGeneric_screen_init(void);
extern void ui_ScreenConfigurationGeneric_screen_destroy(void);
extern lv_obj_t * ui_ScreenConfigurationGeneric;
extern lv_obj_t * ui_ScreenHomeLabel1;
extern lv_obj_t * ui_datetimelabel3;
extern lv_obj_t * ui_ConfSystem1;
extern void ui_event_rollerConfAlertes(lv_event_t * e);
extern lv_obj_t * ui_rollerConfAlertes;
extern void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_ConfSystem2;
extern lv_obj_t * ui_labelConfiguration;
extern lv_obj_t * ui_confLabel1;
extern lv_obj_t * ui_confLabel2;
extern lv_obj_t * ui_confLabel3;
extern void ui_event_confValue1(lv_event_t * e);
extern lv_obj_t * ui_confValue1;
extern lv_obj_t * ui_confValue2;
extern lv_obj_t * ui_confValue3;
extern lv_obj_t * ui_confCancelButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_confSaveButton1;
extern lv_obj_t * ui_Label3;
extern void ui_event_confBackIcon(lv_event_t * e);
extern lv_obj_t * ui_confBackIcon;
extern lv_obj_t * ui_Label4;
extern void ui_event_confNextIcon(lv_event_t * e);
extern lv_obj_t * ui_confNextIcon;
extern void ui_event_confEditIcon1(lv_event_t * e);
extern lv_obj_t * ui_confEditIcon1;
extern lv_obj_t * ui_confEditIcon2;
extern lv_obj_t * ui_confEditIcon3;
extern void ui_event_KeyboardConf(lv_event_t * e);
extern lv_obj_t * ui_KeyboardConf;
extern void ui_event_Slider1Conf(lv_event_t * e);
extern lv_obj_t * ui_Slider1Conf;
extern void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern void ui_event_menuHomeLabel1(lv_event_t * e);
extern lv_obj_t * ui_menuHomeLabel1;
extern lv_obj_t * ui_menuAlertesLabel1;
extern lv_obj_t * ui_menuExportLabel1;
extern lv_obj_t * ui_menuAnalysesLabel1;
extern void ui_event_menuConfigLabel1(lv_event_t * e);
extern lv_obj_t * ui_menuConfigLabel1;
extern void ui_event_Slider2Conf(lv_event_t * e);
extern lv_obj_t * ui_Slider2Conf;
extern lv_obj_t * ui_symboleConfOkValue1;
extern lv_obj_t * ui_symboleConfOkValue2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_rollerConfAlertes;
extern lv_obj_t * uic_labelConfigurateurAlertes;
extern lv_obj_t * uic_confLabel1;
extern lv_obj_t * uic_confLabel2;
extern lv_obj_t * uic_confLabel3;
extern lv_obj_t * uic_confCancelButton;
extern lv_obj_t * uic_confBackIcon;
extern lv_obj_t * uic_confNextIcon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

