// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#include "ui.h"

lv_obj_t * uic_ConfSystemContainerTitreLabel;
lv_obj_t * uic_ConfSystem;
lv_obj_t * uic_ConfNetworkContainerTitreLabel;
lv_obj_t * uic_ConfNetwork;
lv_obj_t * uic_ConfAlertTitreLabel;
lv_obj_t * uic_ConfAlertContainer;
lv_obj_t * uic_ConfSensorContainerTitreLabel;
lv_obj_t * uic_ConfsensorContainer;
lv_obj_t * uic_ScreenHomeLabel;
lv_obj_t * ui_ScreenConfMain;
lv_obj_t * ui_ScreenHomeLabel;
lv_obj_t * ui_ConfsensorContainer;
lv_obj_t * ui_ConfSensorContainerTitreLabel;
lv_obj_t * ui_datetimelabel1;
lv_obj_t * ui_ConfAlertContainer;
lv_obj_t * ui_ConfAlertTitreLabel;
lv_obj_t * ui_ConfNetwork;
lv_obj_t * ui_ConfNetworkContainerTitreLabel;
lv_obj_t * ui_ConfSystem;
lv_obj_t * ui_ConfSystemContainerTitreLabel;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_menuHomeLabel2;
lv_obj_t * ui_menuAlertesLabel2;
lv_obj_t * ui_menuExportLabel2;
lv_obj_t * ui_menuAnalysesLabel2;
lv_obj_t * ui_menuConfigLabel2;

// event funtions
void ui_event_ConfsensorContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_module_config_sensor(e);
    }
}

void ui_event_ConfAlertContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_module_config_alerte(e);
    }
}

void ui_event_ConfNetwork(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_module_config_network(e);
    }
}

void ui_event_ConfSystem(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        show_module_config_system(e);
    }
}

void ui_event_Image3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuHomeLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuAlertesLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuExportLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuAnalysesLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuConfigLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Panel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_menuHomeLabel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenHome_screen_init);
        _ui_flag_modify(ui_Panel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuHomeLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAlertesLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuExportLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAnalysesLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuConfigLabel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_menuConfigLabel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_menuHomeLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAlertesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuExportLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAnalysesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuConfigLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_ScreenConfMain_screen_init(void)
{
    ui_ScreenConfMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenConfMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenConfMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenConfMain, lv_color_hex(0x195FC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenConfMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScreenConfMain, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreenConfMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenConfMain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenHomeLabel = lv_label_create(ui_ScreenConfMain);
    lv_obj_set_width(ui_ScreenHomeLabel, lv_pct(98));
    lv_obj_set_height(ui_ScreenHomeLabel, lv_pct(31));
    lv_obj_set_x(ui_ScreenHomeLabel, 1);
    lv_obj_set_y(ui_ScreenHomeLabel, -104);
    lv_obj_set_align(ui_ScreenHomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenHomeLabel, "\nVCITY  DASHBOARD ");
    lv_obj_set_style_text_color(ui_ScreenHomeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenHomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenHomeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ScreenHomeLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenHomeLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenHomeLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenHomeLabel, lv_color_hex(0x71AA38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ScreenHomeLabel, lv_color_hex(0x8A7E7E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ScreenHomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScreenHomeLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScreenHomeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ScreenHomeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ScreenHomeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenHomeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenHomeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenHomeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenHomeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfsensorContainer = lv_obj_create(ui_ScreenConfMain);
    lv_obj_remove_style_all(ui_ConfsensorContainer);
    lv_obj_set_width(ui_ConfsensorContainer, 146);
    lv_obj_set_height(ui_ConfsensorContainer, 109);
    lv_obj_set_x(ui_ConfsensorContainer, 9);
    lv_obj_set_y(ui_ConfsensorContainer, -29);
    lv_obj_set_align(ui_ConfsensorContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConfsensorContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfsensorContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfsensorContainer, lv_color_hex(0xE27708), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfsensorContainer, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfsensorContainer, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfsensorContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfsensorContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_width(ui_ConfsensorContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ConfsensorContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ConfsensorContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ConfsensorContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ConfSensorContainerTitreLabel = lv_label_create(ui_ConfsensorContainer);
    lv_obj_set_width(ui_ConfSensorContainerTitreLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfSensorContainerTitreLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfSensorContainerTitreLabel, 2);
    lv_obj_set_y(ui_ConfSensorContainerTitreLabel, -3);
    lv_obj_set_align(ui_ConfSensorContainerTitreLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfSensorContainerTitreLabel, "Configuration\nCapteurs ");
    lv_obj_set_style_text_color(ui_ConfSensorContainerTitreLabel, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfSensorContainerTitreLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConfSensorContainerTitreLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ConfSensorContainerTitreLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfSensorContainerTitreLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datetimelabel1 = lv_label_create(ui_ScreenConfMain);
    lv_obj_set_width(ui_datetimelabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_datetimelabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datetimelabel1, -185);
    lv_obj_set_y(ui_datetimelabel1, 148);
    lv_obj_set_align(ui_datetimelabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_datetimelabel1, "08/08/2025 11h27 	");
    lv_obj_set_style_text_color(ui_datetimelabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_datetimelabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_datetimelabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_datetimelabel1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_datetimelabel1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_datetimelabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_datetimelabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_datetimelabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_datetimelabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_datetimelabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfAlertContainer = lv_obj_create(ui_ScreenConfMain);
    lv_obj_remove_style_all(ui_ConfAlertContainer);
    lv_obj_set_width(ui_ConfAlertContainer, 146);
    lv_obj_set_height(ui_ConfAlertContainer, 109);
    lv_obj_set_x(ui_ConfAlertContainer, 160);
    lv_obj_set_y(ui_ConfAlertContainer, -29);
    lv_obj_set_align(ui_ConfAlertContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConfAlertContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfAlertContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfAlertContainer, lv_color_hex(0xE27708), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfAlertContainer, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfAlertContainer, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfAlertContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfAlertContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_width(ui_ConfAlertContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ConfAlertContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ConfAlertContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ConfAlertContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ConfAlertTitreLabel = lv_label_create(ui_ConfAlertContainer);
    lv_obj_set_width(ui_ConfAlertTitreLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfAlertTitreLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfAlertTitreLabel, 2);
    lv_obj_set_y(ui_ConfAlertTitreLabel, -3);
    lv_obj_set_align(ui_ConfAlertTitreLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfAlertTitreLabel, "Configuration\nAlertes");
    lv_obj_set_style_text_color(ui_ConfAlertTitreLabel, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfAlertTitreLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConfAlertTitreLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ConfAlertTitreLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfAlertTitreLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfNetwork = lv_obj_create(ui_ScreenConfMain);
    lv_obj_remove_style_all(ui_ConfNetwork);
    lv_obj_set_width(ui_ConfNetwork, 146);
    lv_obj_set_height(ui_ConfNetwork, 109);
    lv_obj_set_x(ui_ConfNetwork, 8);
    lv_obj_set_y(ui_ConfNetwork, 84);
    lv_obj_set_align(ui_ConfNetwork, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConfNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfNetwork, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfNetwork, lv_color_hex(0xE27708), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfNetwork, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfNetwork, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfNetwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfNetwork, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_width(ui_ConfNetwork, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ConfNetwork, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ConfNetwork, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ConfNetwork, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ConfNetworkContainerTitreLabel = lv_label_create(ui_ConfNetwork);
    lv_obj_set_width(ui_ConfNetworkContainerTitreLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfNetworkContainerTitreLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfNetworkContainerTitreLabel, 2);
    lv_obj_set_y(ui_ConfNetworkContainerTitreLabel, -3);
    lv_obj_set_align(ui_ConfNetworkContainerTitreLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfNetworkContainerTitreLabel, "Configuration\nReseaux");
    lv_obj_set_style_text_color(ui_ConfNetworkContainerTitreLabel, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfNetworkContainerTitreLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConfNetworkContainerTitreLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ConfNetworkContainerTitreLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfNetworkContainerTitreLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfSystem = lv_obj_create(ui_ScreenConfMain);
    lv_obj_remove_style_all(ui_ConfSystem);
    lv_obj_set_width(ui_ConfSystem, 146);
    lv_obj_set_height(ui_ConfSystem, 109);
    lv_obj_set_x(ui_ConfSystem, 160);
    lv_obj_set_y(ui_ConfSystem, 86);
    lv_obj_set_align(ui_ConfSystem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConfSystem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfSystem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfSystem, lv_color_hex(0xE27708), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfSystem, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ConfSystem, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfSystem, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfSystem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfSystem, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_width(ui_ConfSystem, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ConfSystem, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ConfSystem, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ConfSystem, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ConfSystemContainerTitreLabel = lv_label_create(ui_ConfSystem);
    lv_obj_set_width(ui_ConfSystemContainerTitreLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfSystemContainerTitreLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfSystemContainerTitreLabel, 2);
    lv_obj_set_y(ui_ConfSystemContainerTitreLabel, -3);
    lv_obj_set_align(ui_ConfSystemContainerTitreLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfSystemContainerTitreLabel, "Configuration\nSysteme");
    lv_obj_set_style_text_color(ui_ConfSystemContainerTitreLabel, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfSystemContainerTitreLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConfSystemContainerTitreLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ConfSystemContainerTitreLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfSystemContainerTitreLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_ScreenConfMain);
    lv_img_set_src(ui_Image3, &ui_img_128379994);
    lv_obj_set_width(ui_Image3, 50);
    lv_obj_set_height(ui_Image3, 30);
    lv_obj_set_x(ui_Image3, -190);
    lv_obj_set_y(ui_Image3, -63);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Panel3 = lv_obj_create(ui_ScreenConfMain);
    lv_obj_set_width(ui_Panel3, 175);
    lv_obj_set_height(ui_Panel3, 239);
    lv_obj_set_x(ui_Panel3, -141);
    lv_obj_set_y(ui_Panel3, 16);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_menuHomeLabel2 = lv_label_create(ui_ScreenConfMain);
    lv_obj_set_width(ui_menuHomeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuHomeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuHomeLabel2, -157);
    lv_obj_set_y(ui_menuHomeLabel2, -63);
    lv_obj_set_align(ui_menuHomeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuHomeLabel2, "home");
    lv_obj_add_flag(ui_menuHomeLabel2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuHomeLabel2, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuHomeLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuHomeLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuAlertesLabel2 = lv_label_create(ui_ScreenConfMain);
    lv_obj_set_width(ui_menuAlertesLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAlertesLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuAlertesLabel2, -159);
    lv_obj_set_y(ui_menuAlertesLabel2, -26);
    lv_obj_set_align(ui_menuAlertesLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAlertesLabel2, "Alertes");
    lv_obj_add_flag(ui_menuAlertesLabel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_menuAlertesLabel2, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuAlertesLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAlertesLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuExportLabel2 = lv_label_create(ui_ScreenConfMain);
    lv_obj_set_width(ui_menuExportLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuExportLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuExportLabel2, -161);
    lv_obj_set_y(ui_menuExportLabel2, 53);
    lv_obj_set_align(ui_menuExportLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuExportLabel2, "Export");
    lv_obj_add_flag(ui_menuExportLabel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_menuExportLabel2, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuExportLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuExportLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuAnalysesLabel2 = lv_label_create(ui_ScreenConfMain);
    lv_obj_set_width(ui_menuAnalysesLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAnalysesLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuAnalysesLabel2, -160);
    lv_obj_set_y(ui_menuAnalysesLabel2, 11);
    lv_obj_set_align(ui_menuAnalysesLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAnalysesLabel2, "Analyses");
    lv_obj_add_flag(ui_menuAnalysesLabel2,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuAnalysesLabel2, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuAnalysesLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAnalysesLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuConfigLabel2 = lv_label_create(ui_ScreenConfMain);
    lv_obj_set_width(ui_menuConfigLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuConfigLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuConfigLabel2, -161);
    lv_obj_set_y(ui_menuConfigLabel2, 94);
    lv_obj_set_align(ui_menuConfigLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuConfigLabel2, "Settings");
    lv_obj_add_flag(ui_menuConfigLabel2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuConfigLabel2, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuConfigLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuConfigLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ConfsensorContainer, ui_event_ConfsensorContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfAlertContainer, ui_event_ConfAlertContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfNetwork, ui_event_ConfNetwork, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfSystem, ui_event_ConfSystem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuHomeLabel2, ui_event_menuHomeLabel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuConfigLabel2, ui_event_menuConfigLabel2, LV_EVENT_ALL, NULL);
    uic_ScreenHomeLabel = ui_ScreenHomeLabel;
    uic_ConfsensorContainer = ui_ConfsensorContainer;
    uic_ConfSensorContainerTitreLabel = ui_ConfSensorContainerTitreLabel;
    uic_ConfAlertContainer = ui_ConfAlertContainer;
    uic_ConfAlertTitreLabel = ui_ConfAlertTitreLabel;
    uic_ConfNetwork = ui_ConfNetwork;
    uic_ConfNetworkContainerTitreLabel = ui_ConfNetworkContainerTitreLabel;
    uic_ConfSystem = ui_ConfSystem;
    uic_ConfSystemContainerTitreLabel = ui_ConfSystemContainerTitreLabel;

}

void ui_ScreenConfMain_screen_destroy(void)
{
    if(ui_ScreenConfMain) lv_obj_del(ui_ScreenConfMain);

    // NULL screen variables
    ui_ScreenConfMain = NULL;
    uic_ScreenHomeLabel = NULL;
    ui_ScreenHomeLabel = NULL;
    uic_ConfsensorContainer = NULL;
    ui_ConfsensorContainer = NULL;
    uic_ConfSensorContainerTitreLabel = NULL;
    ui_ConfSensorContainerTitreLabel = NULL;
    ui_datetimelabel1 = NULL;
    uic_ConfAlertContainer = NULL;
    ui_ConfAlertContainer = NULL;
    uic_ConfAlertTitreLabel = NULL;
    ui_ConfAlertTitreLabel = NULL;
    uic_ConfNetwork = NULL;
    ui_ConfNetwork = NULL;
    uic_ConfNetworkContainerTitreLabel = NULL;
    ui_ConfNetworkContainerTitreLabel = NULL;
    uic_ConfSystem = NULL;
    ui_ConfSystem = NULL;
    uic_ConfSystemContainerTitreLabel = NULL;
    ui_ConfSystemContainerTitreLabel = NULL;
    ui_Image3 = NULL;
    ui_Panel3 = NULL;
    ui_menuHomeLabel2 = NULL;
    ui_menuAlertesLabel2 = NULL;
    ui_menuExportLabel2 = NULL;
    ui_menuAnalysesLabel2 = NULL;
    ui_menuConfigLabel2 = NULL;

}
