// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#ifndef UI_SCREENCONFMAIN_H
#define UI_SCREENCONFMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenConfMain
extern void ui_ScreenConfMain_screen_init(void);
extern void ui_ScreenConfMain_screen_destroy(void);
extern lv_obj_t * ui_ScreenConfMain;
extern lv_obj_t * ui_ScreenHomeLabel;
extern void ui_event_ConfsensorContainer(lv_event_t * e);
extern lv_obj_t * ui_ConfsensorContainer;
extern lv_obj_t * ui_ConfSensorContainerTitreLabel;
extern lv_obj_t * ui_datetimelabel1;
extern void ui_event_ConfAlertContainer(lv_event_t * e);
extern lv_obj_t * ui_ConfAlertContainer;
extern lv_obj_t * ui_ConfAlertTitreLabel;
extern void ui_event_ConfNetwork(lv_event_t * e);
extern lv_obj_t * ui_ConfNetwork;
extern lv_obj_t * ui_ConfNetworkContainerTitreLabel;
extern void ui_event_ConfSystem(lv_event_t * e);
extern lv_obj_t * ui_ConfSystem;
extern lv_obj_t * ui_ConfSystemContainerTitreLabel;
extern void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
extern void ui_event_menuHomeLabel2(lv_event_t * e);
extern lv_obj_t * ui_menuHomeLabel2;
extern lv_obj_t * ui_menuAlertesLabel2;
extern lv_obj_t * ui_menuExportLabel2;
extern lv_obj_t * ui_menuAnalysesLabel2;
extern void ui_event_menuConfigLabel2(lv_event_t * e);
extern lv_obj_t * ui_menuConfigLabel2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenHomeLabel;
extern lv_obj_t * uic_ConfsensorContainer;
extern lv_obj_t * uic_ConfSensorContainerTitreLabel;
extern lv_obj_t * uic_ConfAlertContainer;
extern lv_obj_t * uic_ConfAlertTitreLabel;
extern lv_obj_t * uic_ConfNetwork;
extern lv_obj_t * uic_ConfNetworkContainerTitreLabel;
extern lv_obj_t * uic_ConfSystem;
extern lv_obj_t * uic_ConfSystemContainerTitreLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

