// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: v4

#include "ui.h"

lv_obj_t * uic_menuConfigLabel;
lv_obj_t * uic_menuAnalysesLabel;
lv_obj_t * uic_menuExportLabel;
lv_obj_t * uic_menuAlertesLabel;
lv_obj_t * uic_menuHomeLabel;
lv_obj_t * uic_datetimelabel;
lv_obj_t * uic_AlerteContainerTitreLabel;
lv_obj_t * uic_AlerteContainer;
lv_obj_t * uic_ScreenHome;
lv_obj_t * ui_ScreenHome;
lv_obj_t * ui_Label1;
lv_obj_t * ui_AlerteContainer;
lv_obj_t * ui_AlerteContainerTitreLabel;
lv_obj_t * ui_datetimelabel;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_menuHomeLabel;
lv_obj_t * ui_menuAlertesLabel;
lv_obj_t * ui_menuExportLabel;
lv_obj_t * ui_menuAnalysesLabel;
lv_obj_t * ui_menuConfigLabel;
lv_obj_t * ui_homeAlerteContainer;
lv_obj_t * ui_homeAlerteIcon;
lv_obj_t * ui_homeAlerteLabel;
lv_obj_t * ui_homeBackIcon;
lv_obj_t * ui_HomeNextIcon;
lv_obj_t * ui_Label6;

// event funtions
void ui_event_ScreenHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuHomeLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAlertesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuExportLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAnalysesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuConfigLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Label1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuHomeLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAlertesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuExportLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAnalysesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuConfigLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuHomeLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuAlertesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuExportLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuAnalysesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menuConfigLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_menuAnalysesLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenAnalyse, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenAnalyse_screen_init);
    }
}

void ui_event_menuConfigLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_menuHomeLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAlertesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuExportLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuAnalysesLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_menuConfigLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_screen_change(&ui_ScreenConfMain, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenConfMain_screen_init);
        _ui_screen_delete(&ui_ScreenHome);
    }
}

void ui_event_homeBackIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        home_alert_back_controller(e);
    }
}

void ui_event_HomeNextIcon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        home_alert_next_controller(e);
    }
}

// build funtions

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_add_flag(ui_ScreenHome, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_ScreenHome, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenHome, lv_color_hex(0x195FC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScreenHome, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScreenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenHome, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_Label1, lv_pct(98));
    lv_obj_set_height(ui_Label1, lv_pct(31));
    lv_obj_set_x(ui_Label1, 1);
    lv_obj_set_y(ui_Label1, -104);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "\nVCITY  DASHBOARD ");
    lv_obj_add_flag(ui_Label1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0x71AA38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label1, lv_color_hex(0x8A7E7E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Label1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlerteContainer = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_AlerteContainer);
    lv_obj_set_width(ui_AlerteContainer, 325);
    lv_obj_set_height(ui_AlerteContainer, 213);
    lv_obj_set_x(ui_AlerteContainer, 61);
    lv_obj_set_y(ui_AlerteContainer, 7);
    lv_obj_set_align(ui_AlerteContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AlerteContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlerteContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AlerteContainer, lv_color_hex(0xFF6D05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AlerteContainer, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AlerteContainer, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_AlerteContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_AlerteContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AlerteContainer, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AlerteContainer, lv_color_hex(0xF30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlerteContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_AlerteContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_width(ui_AlerteContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AlerteContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_AlerteContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_AlerteContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_AlerteContainerTitreLabel = lv_label_create(ui_AlerteContainer);
    lv_obj_set_width(ui_AlerteContainerTitreLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlerteContainerTitreLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlerteContainerTitreLabel, 11);
    lv_obj_set_y(ui_AlerteContainerTitreLabel, -89);
    lv_obj_set_align(ui_AlerteContainerTitreLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlerteContainerTitreLabel, "ALERTES");
    lv_obj_set_style_text_color(ui_AlerteContainerTitreLabel, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlerteContainerTitreLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datetimelabel = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_datetimelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_datetimelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_datetimelabel, -13);
    lv_obj_set_y(ui_datetimelabel, 147);
    lv_obj_set_align(ui_datetimelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_datetimelabel,
                      "date systeme : 08/08/2025 11h27 	                           vers HW:			1.0       vers SOFT :	1.0");
    lv_obj_set_style_text_color(ui_datetimelabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_datetimelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_datetimelabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_datetimelabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_datetimelabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_datetimelabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_datetimelabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_datetimelabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_datetimelabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_datetimelabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Image1, &ui_img_128379994);
    lv_obj_set_width(ui_Image1, 50);
    lv_obj_set_height(ui_Image1, 30);
    lv_obj_set_x(ui_Image1, -190);
    lv_obj_set_y(ui_Image1, -63);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Panel1 = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_Panel1, 175);
    lv_obj_set_height(ui_Panel1, 239);
    lv_obj_set_x(ui_Panel1, -141);
    lv_obj_set_y(ui_Panel1, 16);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_menuHomeLabel = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_menuHomeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuHomeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuHomeLabel, -157);
    lv_obj_set_y(ui_menuHomeLabel, -63);
    lv_obj_set_align(ui_menuHomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuHomeLabel, "home");
    lv_obj_add_flag(ui_menuHomeLabel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuHomeLabel, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuHomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuHomeLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuAlertesLabel = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_menuAlertesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAlertesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuAlertesLabel, -159);
    lv_obj_set_y(ui_menuAlertesLabel, -26);
    lv_obj_set_align(ui_menuAlertesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAlertesLabel, "Alertes");
    lv_obj_add_flag(ui_menuAlertesLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_menuAlertesLabel, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuAlertesLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAlertesLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuExportLabel = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_menuExportLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuExportLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuExportLabel, -161);
    lv_obj_set_y(ui_menuExportLabel, 53);
    lv_obj_set_align(ui_menuExportLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuExportLabel, "Export");
    lv_obj_add_flag(ui_menuExportLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_menuExportLabel, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuExportLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuExportLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuAnalysesLabel = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_menuAnalysesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuAnalysesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuAnalysesLabel, -160);
    lv_obj_set_y(ui_menuAnalysesLabel, 11);
    lv_obj_set_align(ui_menuAnalysesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuAnalysesLabel, "Analyses");
    lv_obj_add_flag(ui_menuAnalysesLabel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuAnalysesLabel, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuAnalysesLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuAnalysesLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuConfigLabel = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_menuConfigLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menuConfigLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_menuConfigLabel, -161);
    lv_obj_set_y(ui_menuConfigLabel, 94);
    lv_obj_set_align(ui_menuConfigLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menuConfigLabel, "Settings");
    lv_obj_add_flag(ui_menuConfigLabel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_menuConfigLabel, lv_color_hex(0x4B4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_menuConfigLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_menuConfigLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeAlerteContainer = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_homeAlerteContainer);
    lv_obj_set_width(ui_homeAlerteContainer, 294);
    lv_obj_set_height(ui_homeAlerteContainer, 120);
    lv_obj_set_x(ui_homeAlerteContainer, 66);
    lv_obj_set_y(ui_homeAlerteContainer, 1);
    lv_obj_set_align(ui_homeAlerteContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_homeAlerteContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homeAlerteContainer, lv_color_hex(0xFFFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeAlerteContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_homeAlerteContainer, lv_color_hex(0x726F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_homeAlerteContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_homeAlerteContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_homeAlerteContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_homeAlerteContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_homeAlerteContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeAlerteIcon = lv_img_create(ui_homeAlerteContainer);
    lv_img_set_src(ui_homeAlerteIcon, &ui_img_warning_png);
    lv_obj_set_width(ui_homeAlerteIcon, 30);
    lv_obj_set_height(ui_homeAlerteIcon, 30);
    lv_obj_set_x(ui_homeAlerteIcon, -74);
    lv_obj_set_y(ui_homeAlerteIcon, -4);
    lv_obj_set_align(ui_homeAlerteIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeAlerteIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_homeAlerteIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homeAlerteLabel = lv_label_create(ui_homeAlerteContainer);
    lv_obj_set_width(ui_homeAlerteLabel, 142);
    lv_obj_set_height(ui_homeAlerteLabel, 72);
    lv_obj_set_x(ui_homeAlerteLabel, 18);
    lv_obj_set_y(ui_homeAlerteLabel, 0);
    lv_obj_set_align(ui_homeAlerteLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_homeAlerteLabel, "absence tension 230V \ndepuis 72H");
    lv_obj_set_style_text_color(ui_homeAlerteLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_homeAlerteLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_homeAlerteLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_homeAlerteLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_homeAlerteLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_homeAlerteLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_homeAlerteLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_homeAlerteLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_homeAlerteLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_homeAlerteLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeBackIcon = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_homeBackIcon, &ui_img_back30_png);
    lv_obj_set_width(ui_homeBackIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeBackIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_homeBackIcon, 44);
    lv_obj_set_y(ui_homeBackIcon, 87);
    lv_obj_set_align(ui_homeBackIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeBackIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_homeBackIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeNextIcon = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_HomeNextIcon, &ui_img_foward30_png);
    lv_obj_set_width(ui_HomeNextIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeNextIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeNextIcon, 129);
    lv_obj_set_y(ui_HomeNextIcon, 86);
    lv_obj_set_align(ui_HomeNextIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeNextIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeNextIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 86);
    lv_obj_set_y(ui_Label6, 86);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "1/4");

    lv_obj_add_event_cb(ui_Label1, ui_event_Label1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuAnalysesLabel, ui_event_menuAnalysesLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuConfigLabel, ui_event_menuConfigLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeBackIcon, ui_event_homeBackIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeNextIcon, ui_event_HomeNextIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenHome, ui_event_ScreenHome, LV_EVENT_ALL, NULL);
    uic_ScreenHome = ui_ScreenHome;
    uic_AlerteContainer = ui_AlerteContainer;
    uic_AlerteContainerTitreLabel = ui_AlerteContainerTitreLabel;
    uic_datetimelabel = ui_datetimelabel;
    uic_menuHomeLabel = ui_menuHomeLabel;
    uic_menuAlertesLabel = ui_menuAlertesLabel;
    uic_menuExportLabel = ui_menuExportLabel;
    uic_menuAnalysesLabel = ui_menuAnalysesLabel;
    uic_menuConfigLabel = ui_menuConfigLabel;

}

void ui_ScreenHome_screen_destroy(void)
{
    if(ui_ScreenHome) lv_obj_del(ui_ScreenHome);

    // NULL screen variables
    uic_ScreenHome = NULL;
    ui_ScreenHome = NULL;
    ui_Label1 = NULL;
    uic_AlerteContainer = NULL;
    ui_AlerteContainer = NULL;
    uic_AlerteContainerTitreLabel = NULL;
    ui_AlerteContainerTitreLabel = NULL;
    uic_datetimelabel = NULL;
    ui_datetimelabel = NULL;
    ui_Image1 = NULL;
    ui_Panel1 = NULL;
    uic_menuHomeLabel = NULL;
    ui_menuHomeLabel = NULL;
    uic_menuAlertesLabel = NULL;
    ui_menuAlertesLabel = NULL;
    uic_menuExportLabel = NULL;
    ui_menuExportLabel = NULL;
    uic_menuAnalysesLabel = NULL;
    ui_menuAnalysesLabel = NULL;
    uic_menuConfigLabel = NULL;
    ui_menuConfigLabel = NULL;
    ui_homeAlerteContainer = NULL;
    ui_homeAlerteIcon = NULL;
    ui_homeAlerteLabel = NULL;
    ui_homeBackIcon = NULL;
    ui_HomeNextIcon = NULL;
    ui_Label6 = NULL;

}
